name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Configuration
      run: |
        echo "KERNEL_SOURCE=$(cat config.env | grep "KERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "KERNEL_SOURCE_BRANCH=$(cat config.env | grep "KERNEL_SOURCE_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "KERNEL_CONFIG=$(cat config.env | grep "KERNEL_CONFIG" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "ARCH=$(cat config.env | grep "ARCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "KERNEL_FILE=$(cat config.env | grep "KERNEL_FILE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "CLANG_VERSION=$(cat config.env | grep "CLANG_VERSION" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "BUILD_EXTRA_COMMAND=$(cat config.env | grep "EXTRA_BUILD_COMMAND" | head -n 1 | cut -d ":" -f 2- | tr ':' ' ')" >> $GITHUB_ENV
        echo "DISABLE-LTO=$(cat config.env | grep "DISABLE-LTO" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "APPLY_CUSTOM_PATCH=$(cat config.env | grep "APPLY_CUSTOM_PATCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "ENABLE_KERNELSU=$(cat config.env | grep "ENABLE_KERNELSU" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "KERNELSU_SOURCE=$(cat config.env | grep "KERNELSU_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "KERNELSU_REPO_NAME=$(cat config.env | grep "KERNELSU_SOURCE" | head -n 1 | cut -d "=" -f 2 | awk -F "/" '{print $NF}' | sed 's/.git$//')" >> $GITHUB_ENV
        echo "KERNELSU_BRANCH=$(cat config.env | grep "KERNELSU_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "ENABLE_SUSFS=$(cat config.env | grep "ENABLE_SUSFS" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "ENABLE_NOMOUNT=$(cat config.env | grep "ENABLE_NOMOUNT" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "NOMOUNT_BRANCH=$(cat config.env | grep "NOMOUNT_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "ENABLE_BBG=$(cat config.env | grep "ENABLE_BBG" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV

    - name: Setup build kernel environment
      run: |
        echo "BUILD_TIME=$(TZ=Asia/Jakarta date "+%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "DEVICE=$(echo ${{ env.KERNEL_CONFIG }} | sed 's!vendor/!!;s/_defconfig//;s/_user//;s/-perf//' | awk -F "/" '{print $NF}')" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 libncurses6 libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python3 python3-dev swig python-is-python3 python2 texinfo rng-tools
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace

    - name: Cache Clang Toolchain
      uses: actions/cache@v4
      id: cache-clang
      with:
        path: clang-android
        key: clang-android-r416183b

    - name: Download Clang Toolchain
      if: steps.cache-clang.outputs.cache-hit != 'true'
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b.git -b lineage-20.0 clang-android

    - name: Cache GCC Toolchain
      uses: actions/cache@v4
      id: cache-gcc
      with:
        path: gcc-android
        key: gcc-android-ndk-r23

    - name: Download GCC Toolchain
      if: steps.cache-gcc.outputs.cache-hit != 'true'
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b ndk-release-r23 gcc-android

    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ccache-${{ env.DEVICE }}-${{ github.sha }}
        restore-keys: |
          ccache-${{ env.DEVICE }}-

    - name: Download kernel source
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} android-kernel --depth=1
        cd android-kernel
        KERNEL_VER=$(grep -E "(^VERSION|^PATCHLEVEL)" ./Makefile | awk '{print $NF}' | tr '\n' '.' | sed 's/\.$//')
        echo "kernel version: $KERNEL_VER"
        echo "KERNEL_VERSION=$KERNEL_VER" >> $GITHUB_ENV

    - name: Setup ${{ env.KERNELSU_REPO_NAME }}
      if: env.ENABLE_KERNELSU == 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash
        echo "UPLOADNAME=+${{ env.KERNELSU_REPO_NAME }}-${{ env.KERNELSU_BRANCH }}" >> $GITHUB_ENV
        echo "CONFIG_KSU=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}

        # Susfs setup
        if [ ${{ env.ENABLE_SUSFS }} = true ]; then
          git clone https://github.com/JackA1ltman/NonGKI_Kernel_Build_2nd.git
          patch -p1 < ./NonGKI_Kernel_Build_2nd/Patches/Patch/susfs_patch_to_${{ env.KERNEL_VERSION }}.patch
          bash ./NonGKI_Kernel_Build_2nd/Patches/susfs_inline_hook_patches.sh
          echo "CONFIG_KSU_SUSFS=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
          SUS_VER=$(grep 'SUSFS_VERSION' ./include/linux/susfs.h | awk '{print $NF}' | sed 's/"//g')
          echo "WITH_SUSFS=+susfs-$SUS_VER" >> $GITHUB_ENV
        else
          echo "CONFIG_KSU_MANUAL_HOOK=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
          patch -p1 < $GITHUB_WORKSPACE/patch/ksu_hook.patch
        fi

    - name: Setup NoMount
      if: env.ENABLE_NOMOUNT == 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        #git clone https://github.com/maxsteeel/nomount.git -b ${{ env.NOMOUNT_BRANCH }} nomount
        #patch -p1 < ./nomount/kernel/patches/nomount_${{ env.KERNEL_VERSION }}_kernel_integration.patch
        #cp -v ./nomount/kernel/src/nomount.* ./fs/nomount
        wget -O- https://raw.githubusercontent.com/maxsteeel/nomount/refs/heads/experimental/hookless/kernel/setup.sh | bash -s ${{ env.NOMOUNT_BRANCH }}
        echo "CONFIG_NOMOUNT=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
        echo "WITH_NOMOUNT=+nomount" >> $GITHUB_ENV

    - name: Setup Baseband-guard
      if: env.ENABLE_BBG == 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        wget -O- https://github.com/vc-teahouse/Baseband-guard/raw/main/setup.sh | bash
        echo "CONFIG_BBG=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
        echo "WITH_BBG=+bbg" >> $GITHUB_ENV

    - name: Setup Configuration for Kernel
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        if [ ${{ env.APPLY_CUSTOM_PATCH }} = true ] && [ -f $GITHUB_WORKSPACE/patch/custom.patch ]; then
           patch -p1 < $GITHUB_WORKSPACE/patch/custom.patch
        fi

        if [ -f $GITHUB_WORKSPACE/extra_kernel_config ]; then
          while IFS= read -r i || [ -n "$i" ]; do
            [ -z "$i" ] && continue
            # grep -q "^#${i}" && continue
            f=$(echo "$i" | cut -d= -f1)
            if grep -q "^${f}=" arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}; then
              sed -i "s|^${f}=.*|$i|" arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
            else
              echo "$i" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
            fi
          done < "$GITHUB_WORKSPACE/extra_kernel_config"
        fi

        export PATH=$GITHUB_WORKSPACE/clang-android/bin:$GITHUB_WORKSPACE/gcc-android/bin:$PATH
        export ARCH=${{ env.ARCH }}
        export SUBARCH=${{ env.ARCH }}
        export KBUILD_COMPILER_STRING="$(clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')"
        export KBUILD_BUILD_HOST=ubuntu
        export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
        export DTC_EXT=dtc

        make -j$(nproc --all) \
         O=out ARCH=${{ env.ARCH }} \
         CC=clang \
         LOCALVERSION=-perf \
         LLVM=1 \
         CLANG_TRIPLE=aarch64-linux-gnu- \
         CROSS_COMPILE=aarch64-linux-android- ${{ env.KERNEL_CONFIG }}

    - name: Build kernel
      run: |
        set -o pipefail
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        export PATH=$GITHUB_WORKSPACE/clang-android/bin:$GITHUB_WORKSPACE/gcc-android/bin:$PATH
        export ARCH=${{ env.ARCH }}
        export SUBARCH=${{ env.ARCH }}
        export KBUILD_COMPILER_STRING="$(clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')"
        export KBUILD_BUILD_HOST=ubuntu
        export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
        export DTC_EXT=dtc
        export CCACHE_DIR=~/.ccache
        export USE_CCACHE=1

        make -j$(nproc --all) \
         O=out ARCH=arm64 \
         CC=clang \
         LOCALVERSION=-perf \
         LLVM=1 \
         CLANG_TRIPLE=aarch64-linux-gnu- \
         CROSS_COMPILE=aarch64-linux-android- savedefconfig

        cp -f out/defconfig arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}

        make -j$(nproc --all) \
         O=out ARCH=${{ env.ARCH }} \
         CC="ccache clang" \
         LOCALVERSION=-perf \
         LLVM=1 \
         CLANG_TRIPLE=aarch64-linux-gnu- \
         CROSS_COMPILE=aarch64-linux-android- ${{ env.BUILD_EXTRA_COMMAND }} 2>&1 | tee $GITHUB_WORKSPACE/build.log

    - name: Check a kernel output files
      run: |
       cd $GITHUB_WORKSPACE/kernel_workspace
       if [ -f android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_FILE }} ]; then
           strings android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_FILE }} | grep -Ei "linux version [0-9].*"
           echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV
       else
           echo "Kernel output file is empty"
       fi

    - name: Prepare kernel files
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/out/arch/${{ env.ARCH }}/boot
        cp -v $GITHUB_WORKSPACE/kernel_workspace/android-kernel/out/.config kernel_configs.txt
        [ -d $GITHUB_WORKSPACE/kernel_workspace/android-kernel/out/certs ] && \
          cp -rv $GITHUB_WORKSPACE/kernel_workspace/android-kernel/out/certs .
        cp -v $GITHUB_WORKSPACE/build.log build.log
        find $GITHUB_WORKSPACE/kernel_workspace/android-kernel/out -type f -name "*.ko" | while read file; do cp -rv $file .; done

    - name: Upload Kernel Image only
      if: env.CHECK_FILE_IS_OK == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_FILE }}-${{ env.DEVICE }}${{ env.UPLOADNAME }}${{ env.WITH_SUSFS }}${{ env.WITH_NOMOUNT }}${{ env.WITH_BBG }}-${{ env.BUILD_TIME }}-Image-only
        path: kernel_workspace/android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_FILE }}

    - name: Upload Kernel Full (config, boot, modules)
      if: env.CHECK_FILE_IS_OK == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_FILE }}-${{ env.DEVICE }}${{ env.UPLOADNAME }}${{ env.WITH_SUSFS }}${{ env.WITH_NOMOUNT }}${{ env.WITH_BBG }}-${{ env.BUILD_TIME }}-full
        path: kernel_workspace/android-kernel/out/arch/${{ env.ARCH }}/boot/

    - name: Upload build log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-log-${{ env.BUILD_TIME }}
        path: build.log